# Generated by Django 4.0.3 on 2023-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_jobapply_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='from_date',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='task_date',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
