# Generated by Django 4.0.3 on 2023-08-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_contact_employeelogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='resume',
            field=models.FileField(default='null', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='created_at',
            field=models.CharField(default='2023-08-22', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobsrequired',
            name='created_at',
            field=models.CharField(default='2023-08-22', max_length=150),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='created_at',
            field=models.CharField(default='2023-08-22', max_length=150),
        ),
        migrations.AlterField(
            model_name='telemetrydaa',
            name='date',
            field=models.CharField(default='2023-08-22', max_length=10),
        ),
    ]
