# Generated by Django 4.0.3 on 2023-11-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_jobapply_created_at_and_more'),
        ('account', '0014_alter_jobapply_created_at_and_more'),
        ('account', '0032_alter_jobapply_created_at_and_more'),
    ]

    operations = [
    ]
