# Generated by Django 4.0.3 on 2023-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_merge_20231121_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
        migrations.DeleteModel(
            name='EmployeeLogin',
        ),
        migrations.DeleteModel(
            name='LoginProfile',
        ),
        migrations.AddField(
            model_name='contact',
            name='ads_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='percentage',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='posted_by',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='resume_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='Introduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='created_at',
            field=models.CharField(default='2023-11-21', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='filename',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobsrequired',
            name='created_at',
            field=models.CharField(default='2023-11-21', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobsrequired',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsrequired',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='created_at',
            field=models.CharField(default='2023-11-21', max_length=150),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/images'),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telemetrydaa',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telemetrydaa',
            name='date',
            field=models.CharField(default='2023-11-21', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
