# Generated by Django 4.0.3 on 2024-01-08 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_jobapply_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_devices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='token_expiration_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
        ),
        migrations.AddField(
            model_name='user',
            name='token_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='created_at',
            field=models.CharField(default='2024-01-08', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobsrequired',
            name='created_at',
            field=models.CharField(default='2024-01-08', max_length=150),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='created_at',
            field=models.CharField(default='2024-01-08', max_length=150),
        ),
        migrations.AlterField(
            model_name='telemetrydaa',
            name='date',
            field=models.CharField(default='2024-01-08', max_length=10),
        ),
    ]
