# Generated by Django 4.0.3 on 2023-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0058_businesspricing_chatsupport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='aadhar_card',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pan_card',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
