# Generated by Django 4.0.3 on 2023-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0058_alter_imageadsmodels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspricing',
            name='chatSupport',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesspricing',
            name='dedicatedRm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesspricing',
            name='hol9Website',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesspricing',
            name='teleSupport',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adsmangeme',
            name='date_created',
            field=models.CharField(default='2023-08-21', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdetailsvalues',
            name='date',
            field=models.CharField(default='2023-08-21', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='ads_timing',
            field=models.CharField(default='2023-08-21', max_length=30),
        ),
        migrations.AlterField(
            model_name='realestateenquery',
            name='date_created',
            field=models.CharField(default='2023-08-21', max_length=150),
        ),
        migrations.AlterField(
            model_name='reportads',
            name='dates',
            field=models.CharField(default='2023-08-21', max_length=30),
        ),
    ]
