# Generated by Django 4.0.3 on 2023-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0059_alter_businessprofile_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='aadhar_card',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pan_card',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
