# Generated by Django 4.0.3 on 2023-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0060_alter_businessprofile_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageadsmodels',
            name='image',
            field=models.ImageField(default='null', upload_to='upload/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='null', upload_to='upload/images'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(default='null', upload_to='upload/images'),
        ),
    ]
