# Generated by Django 4.0.3 on 2023-10-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0062_alter_adsmangeme_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauth',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminauth',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminauth',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adscomment',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adscomment',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adsmangeme',
            name='connectMember',
            field=models.CharField(default='srishtisrija@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='adsmangeme',
            name='date_created',
            field=models.CharField(default='2023-10-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesspricing',
            name='NoAds',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesspricing',
            name='OrderID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesspricing',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesspricing',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesspricing',
            name='validity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesspricing',
            name='visiblity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currentdate',
            name='dateFiled',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lastlogin',
            name='lastloginValue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentdetailsvalues',
            name='date',
            field=models.CharField(default='2023-10-01', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='OrderID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='ads_timing',
            field=models.CharField(default='2023-10-01', max_length=30),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='days',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='featured',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='regulars',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='response',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='topAds',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='validity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ApartMentType',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='BuildUpArea',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Flor',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='FurnishedType',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Garden',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Gym',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Lift',
            field=models.CharField(blank=True, default='NoData', max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Parking',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PlanCategory',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pool',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PowerBackup',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Property',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='adsType',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ads_limit',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ads_timing',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='college',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorCheck',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='extraField',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_ads',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kmdriven',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldPetsCheck',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='phoneNumberCollectVisiters',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='registrationYear',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='school',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='setkmDriven',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='setregistrationYear',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizeCheck',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategoryType',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategoryValue',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='support',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_listing',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realestateenquery',
            name='date_created',
            field=models.CharField(default='2023-10-01', max_length=150),
        ),
        migrations.AlterField(
            model_name='reportads',
            name='dates',
            field=models.CharField(default='2023-10-01', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportads',
            name='report',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wishlistdata',
            name='wishlistData',
            field=models.CharField(max_length=255),
        ),
    ]
