# Generated by Django 4.0.3 on 2023-11-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0064_alter_adsmangeme_date_created_and_more'),
        ('adsapi', '0071_assigntask_employeelogin2_and_more'),
    ]

    operations = [
    ]
