# Generated by Django 4.0.3 on 2023-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0072_merge_20231121_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignTask',
        ),
        migrations.DeleteModel(
            name='EmployeeLogin2',
        ),
        migrations.AlterField(
            model_name='adsmangeme',
            name='date_created',
            field=models.CharField(default='2023-11-21', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_document_type',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='imageadsmodels',
            name='image',
            field=models.ImageField(default='null', upload_to='upload/images'),
        ),
        migrations.AlterField(
            model_name='paymentdetailsvalues',
            name='date',
            field=models.CharField(default='2023-11-21', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='ads_timing',
            field=models.CharField(default='2023-11-21', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='PlanCategory',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='adsType',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ads_limit',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ads_timing',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='college',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorCheck',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_ads',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kmdriven',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldPetsCheck',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='phoneNumberCollectVisiters',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='registrationYear',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='school',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='setkmDriven',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='setregistrationYear',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizeCheck',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='support',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_listing',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realestateenquery',
            name='date_created',
            field=models.CharField(default='2023-11-21', max_length=150),
        ),
        migrations.AlterField(
            model_name='reportads',
            name='dates',
            field=models.CharField(default='2023-11-21', max_length=30),
        ),
    ]
