# Generated by Django 4.0.3 on 2024-01-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0041_alter_adscomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscomment',
            name='date',
            field=models.CharField(default='2024-01-04', max_length=10),
        ),
    ]
