# Generated by Django 4.0.3 on 2024-01-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0042_alter_adscomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscomment',
            name='date',
            field=models.CharField(default='2024-01-08', max_length=10),
        ),
    ]
