# Generated by Django 4.0.3 on 2023-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0027_alter_order_order_datetele_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transationidone',
            name='ProductData',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
