# Generated by Django 4.0.3 on 2024-01-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0042_profile_image_base64_alter_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(default='2024-01-01', max_length=10),
        ),
    ]
