# Generated by Django 4.0.3 on 2024-01-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0043_alter_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(default='2024-01-04', max_length=10),
        ),
    ]
